on:
  workflow_dispatch:
  pull_request:
    types:
    - closed
    - opened
    - reopened
    - synchronize

permissions:
  contents: read
  pull-requests: read
  deployments: write

jobs:
  deploy:
    concurrency: codesphere
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: codesphere-cloud/gh-action-deploy@main
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
            email: ${{ secrets.CODESPHERE_EMAIL }}
            password: ${{ secrets.CODESPHERE_PASSWORD }}
            team: ${{ secrets.CODESPHERE_TEAM }}
            plan: 'Boost'
            onDemand: 'true'
            env: |
              TEAM_ID=${{ secrets.CODESPHERE_TEAM_ID }}
              CS_TOKEN=${{ secrets.CODESPHERE_TOKEN }}
